/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DisruptionEvent {
  'timestamp' : Time,
  'affectedZones' : Array<string>,
  'eventType' : DisruptionType,
}
export type DisruptionType = { 'outage' : null } |
  { 'curfew' : null } |
  { 'heat' : null } |
  { 'rain' : null } |
  { 'pollution' : null };
export interface Payout {
  'hours' : bigint,
  'risk' : ZoneRisk,
  'zone' : string,
  'timestamp' : Time,
  'amount' : bigint,
  'eventType' : DisruptionType,
}
export interface PolicyPurchase {
  'risk' : ZoneRisk,
  'zone' : string,
  'timestamp' : Time,
}
export interface RiderProfile {
  'name' : string,
  'zone' : string,
  'zoneRisk' : ZoneRisk,
  'walletBalance' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'zone' : string,
  'zoneRisk' : ZoneRisk,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type ZoneRisk = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculatePayout' : ActorMethod<[bigint, DisruptionType], bigint>,
  'createDisruption' : ActorMethod<[DisruptionType, Array<string>], undefined>,
  'getAllDisruptions' : ActorMethod<[], Array<DisruptionEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPayoutHistory' : ActorMethod<[], Array<Payout>>,
  'getPayoutsByRider' : ActorMethod<[Principal], Array<Payout>>,
  'getPolicyPurchase' : ActorMethod<[Principal], PolicyPurchase>,
  'getRiderProfile' : ActorMethod<[Principal], RiderProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'getZoneCoverage' : ActorMethod<[], Array<[ZoneRisk, bigint]>>,
  'getZonePricing' : ActorMethod<[], Array<[ZoneRisk, bigint]>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchasePolicy' : ActorMethod<[], bigint>,
  'registerRider' : ActorMethod<[string, string, ZoneRisk], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];