/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DisruptionType = IDL.Variant({
  'outage' : IDL.Null,
  'curfew' : IDL.Null,
  'heat' : IDL.Null,
  'rain' : IDL.Null,
  'pollution' : IDL.Null,
});
export const Time = IDL.Int;
export const DisruptionEvent = IDL.Record({
  'timestamp' : Time,
  'affectedZones' : IDL.Vec(IDL.Text),
  'eventType' : DisruptionType,
});
export const ZoneRisk = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'zone' : IDL.Text,
  'zoneRisk' : ZoneRisk,
});
export const Payout = IDL.Record({
  'hours' : IDL.Nat,
  'risk' : ZoneRisk,
  'zone' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'eventType' : DisruptionType,
});
export const PolicyPurchase = IDL.Record({
  'risk' : ZoneRisk,
  'zone' : IDL.Text,
  'timestamp' : Time,
});
export const RiderProfile = IDL.Record({
  'name' : IDL.Text,
  'zone' : IDL.Text,
  'zoneRisk' : ZoneRisk,
  'walletBalance' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculatePayout' : IDL.Func([IDL.Nat, DisruptionType], [IDL.Nat], []),
  'createDisruption' : IDL.Func([DisruptionType, IDL.Vec(IDL.Text)], [], []),
  'getAllDisruptions' : IDL.Func([], [IDL.Vec(DisruptionEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPayoutHistory' : IDL.Func([], [IDL.Vec(Payout)], ['query']),
  'getPayoutsByRider' : IDL.Func([IDL.Principal], [IDL.Vec(Payout)], ['query']),
  'getPolicyPurchase' : IDL.Func([IDL.Principal], [PolicyPurchase], ['query']),
  'getRiderProfile' : IDL.Func([IDL.Principal], [RiderProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getZoneCoverage' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ZoneRisk, IDL.Nat))],
      ['query'],
    ),
  'getZonePricing' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ZoneRisk, IDL.Nat))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchasePolicy' : IDL.Func([], [IDL.Nat], []),
  'registerRider' : IDL.Func([IDL.Text, IDL.Text, ZoneRisk], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DisruptionType = IDL.Variant({
    'outage' : IDL.Null,
    'curfew' : IDL.Null,
    'heat' : IDL.Null,
    'rain' : IDL.Null,
    'pollution' : IDL.Null,
  });
  const Time = IDL.Int;
  const DisruptionEvent = IDL.Record({
    'timestamp' : Time,
    'affectedZones' : IDL.Vec(IDL.Text),
    'eventType' : DisruptionType,
  });
  const ZoneRisk = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'zone' : IDL.Text,
    'zoneRisk' : ZoneRisk,
  });
  const Payout = IDL.Record({
    'hours' : IDL.Nat,
    'risk' : ZoneRisk,
    'zone' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'eventType' : DisruptionType,
  });
  const PolicyPurchase = IDL.Record({
    'risk' : ZoneRisk,
    'zone' : IDL.Text,
    'timestamp' : Time,
  });
  const RiderProfile = IDL.Record({
    'name' : IDL.Text,
    'zone' : IDL.Text,
    'zoneRisk' : ZoneRisk,
    'walletBalance' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculatePayout' : IDL.Func([IDL.Nat, DisruptionType], [IDL.Nat], []),
    'createDisruption' : IDL.Func([DisruptionType, IDL.Vec(IDL.Text)], [], []),
    'getAllDisruptions' : IDL.Func([], [IDL.Vec(DisruptionEvent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPayoutHistory' : IDL.Func([], [IDL.Vec(Payout)], ['query']),
    'getPayoutsByRider' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Payout)],
        ['query'],
      ),
    'getPolicyPurchase' : IDL.Func(
        [IDL.Principal],
        [PolicyPurchase],
        ['query'],
      ),
    'getRiderProfile' : IDL.Func([IDL.Principal], [RiderProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getZoneCoverage' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ZoneRisk, IDL.Nat))],
        ['query'],
      ),
    'getZonePricing' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ZoneRisk, IDL.Nat))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchasePolicy' : IDL.Func([], [IDL.Nat], []),
    'registerRider' : IDL.Func([IDL.Text, IDL.Text, ZoneRisk], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };