/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface RiderProfile {
    name: string;
    zone: string;
    zoneRisk: ZoneRisk;
    walletBalance: bigint;
}
export interface Payout {
    hours: bigint;
    risk: ZoneRisk;
    zone: string;
    timestamp: Time;
    amount: bigint;
    eventType: DisruptionType;
}
export interface PolicyPurchase {
    risk: ZoneRisk;
    zone: string;
    timestamp: Time;
}
export interface DisruptionEvent {
    timestamp: Time;
    affectedZones: Array<string>;
    eventType: DisruptionType;
}
export interface UserProfile {
    name: string;
    zone: string;
    zoneRisk: ZoneRisk;
}
export enum DisruptionType {
    outage = "outage",
    curfew = "curfew",
    heat = "heat",
    rain = "rain",
    pollution = "pollution"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum ZoneRisk {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculatePayout(hours: bigint, eventType: DisruptionType): Promise<bigint>;
    createDisruption(eventType: DisruptionType, affectedZones: Array<string>): Promise<void>;
    getAllDisruptions(): Promise<Array<DisruptionEvent>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPayoutHistory(): Promise<Array<Payout>>;
    getPayoutsByRider(rider: Principal): Promise<Array<Payout>>;
    getPolicyPurchase(rider: Principal): Promise<PolicyPurchase>;
    getRiderProfile(rider: Principal): Promise<RiderProfile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWalletBalance(): Promise<bigint>;
    getZoneCoverage(): Promise<Array<[ZoneRisk, bigint]>>;
    getZonePricing(): Promise<Array<[ZoneRisk, bigint]>>;
    isCallerAdmin(): Promise<boolean>;
    purchasePolicy(): Promise<bigint>;
    registerRider(name: string, zone: string, risk: ZoneRisk): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { DisruptionEvent as _DisruptionEvent, DisruptionType as _DisruptionType, Payout as _Payout, PolicyPurchase as _PolicyPurchase, RiderProfile as _RiderProfile, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, ZoneRisk as _ZoneRisk } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculatePayout(arg0: bigint, arg1: DisruptionType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculatePayout(arg0, to_candid_DisruptionType_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculatePayout(arg0, to_candid_DisruptionType_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDisruption(arg0: DisruptionType, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDisruption(to_candid_DisruptionType_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDisruption(to_candid_DisruptionType_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async getAllDisruptions(): Promise<Array<DisruptionEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDisruptions();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDisruptions();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayoutHistory(): Promise<Array<Payout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayoutHistory();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayoutHistory();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayoutsByRider(arg0: Principal): Promise<Array<Payout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayoutsByRider(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayoutsByRider(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPolicyPurchase(arg0: Principal): Promise<PolicyPurchase> {
        if (this.processError) {
            try {
                const result = await this.actor.getPolicyPurchase(arg0);
                return from_candid_PolicyPurchase_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPolicyPurchase(arg0);
            return from_candid_PolicyPurchase_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiderProfile(arg0: Principal): Promise<RiderProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiderProfile(arg0);
                return from_candid_RiderProfile_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiderProfile(arg0);
            return from_candid_RiderProfile_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance();
            return result;
        }
    }
    async getZoneCoverage(): Promise<Array<[ZoneRisk, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getZoneCoverage();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZoneCoverage();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getZonePricing(): Promise<Array<[ZoneRisk, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getZonePricing();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZonePricing();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async purchasePolicy(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.purchasePolicy();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchasePolicy();
            return result;
        }
    }
    async registerRider(arg0: string, arg1: string, arg2: ZoneRisk): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerRider(arg0, arg1, to_candid_ZoneRisk_n26(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerRider(arg0, arg1, to_candid_ZoneRisk_n26(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DisruptionEvent_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisruptionEvent): DisruptionEvent {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_DisruptionType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisruptionType): DisruptionType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Payout_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payout): Payout {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PolicyPurchase_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PolicyPurchase): PolicyPurchase {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_RiderProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiderProfile): RiderProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ZoneRisk_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ZoneRisk): ZoneRisk {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    zone: string;
    zoneRisk: _ZoneRisk;
}): {
    name: string;
    zone: string;
    zoneRisk: ZoneRisk;
} {
    return {
        name: value.name,
        zone: value.zone,
        zoneRisk: from_candid_ZoneRisk_n13(_uploadFile, _downloadFile, value.zoneRisk)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hours: bigint;
    risk: _ZoneRisk;
    zone: string;
    timestamp: _Time;
    amount: bigint;
    eventType: _DisruptionType;
}): {
    hours: bigint;
    risk: ZoneRisk;
    zone: string;
    timestamp: Time;
    amount: bigint;
    eventType: DisruptionType;
} {
    return {
        hours: value.hours,
        risk: from_candid_ZoneRisk_n13(_uploadFile, _downloadFile, value.risk),
        zone: value.zone,
        timestamp: value.timestamp,
        amount: value.amount,
        eventType: from_candid_DisruptionType_n8(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    risk: _ZoneRisk;
    zone: string;
    timestamp: _Time;
}): {
    risk: ZoneRisk;
    zone: string;
    timestamp: Time;
} {
    return {
        risk: from_candid_ZoneRisk_n13(_uploadFile, _downloadFile, value.risk),
        zone: value.zone,
        timestamp: value.timestamp
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    zone: string;
    zoneRisk: _ZoneRisk;
    walletBalance: bigint;
}): {
    name: string;
    zone: string;
    zoneRisk: ZoneRisk;
    walletBalance: bigint;
} {
    return {
        name: value.name,
        zone: value.zone,
        zoneRisk: from_candid_ZoneRisk_n13(_uploadFile, _downloadFile, value.zoneRisk),
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timestamp: _Time;
    affectedZones: Array<string>;
    eventType: _DisruptionType;
}): {
    timestamp: Time;
    affectedZones: Array<string>;
    eventType: DisruptionType;
} {
    return {
        timestamp: value.timestamp,
        affectedZones: value.affectedZones,
        eventType: from_candid_DisruptionType_n8(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ZoneRisk, bigint]): [ZoneRisk, bigint] {
    return [
        from_candid_ZoneRisk_n13(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): ZoneRisk {
    return "low" in value ? ZoneRisk.low : "high" in value ? ZoneRisk.high : "medium" in value ? ZoneRisk.medium : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outage: null;
} | {
    curfew: null;
} | {
    heat: null;
} | {
    rain: null;
} | {
    pollution: null;
}): DisruptionType {
    return "outage" in value ? DisruptionType.outage : "curfew" in value ? DisruptionType.curfew : "heat" in value ? DisruptionType.heat : "rain" in value ? DisruptionType.rain : "pollution" in value ? DisruptionType.pollution : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payout>): Array<Payout> {
    return value.map((x)=>from_candid_Payout_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ZoneRisk, bigint]>): Array<[ZoneRisk, bigint]> {
    return value.map((x)=>from_candid_tuple_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DisruptionEvent>): Array<DisruptionEvent> {
    return value.map((x)=>from_candid_DisruptionEvent_n6(_uploadFile, _downloadFile, x));
}
function to_candid_DisruptionType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisruptionType): _DisruptionType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ZoneRisk_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ZoneRisk): _ZoneRisk {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    zone: string;
    zoneRisk: ZoneRisk;
}): {
    name: string;
    zone: string;
    zoneRisk: _ZoneRisk;
} {
    return {
        name: value.name,
        zone: value.zone,
        zoneRisk: to_candid_ZoneRisk_n26(_uploadFile, _downloadFile, value.zoneRisk)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ZoneRisk): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == ZoneRisk.low ? {
        low: null
    } : value == ZoneRisk.high ? {
        high: null
    } : value == ZoneRisk.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisruptionType): {
    outage: null;
} | {
    curfew: null;
} | {
    heat: null;
} | {
    rain: null;
} | {
    pollution: null;
} {
    return value == DisruptionType.outage ? {
        outage: null
    } : value == DisruptionType.curfew ? {
        curfew: null
    } : value == DisruptionType.heat ? {
        heat: null
    } : value == DisruptionType.rain ? {
        rain: null
    } : value == DisruptionType.pollution ? {
        pollution: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
